[package]
name = "banyanfs"
description = "A first pass implmentation of a BanyanFS format and platform client all-in-one. Spec reference implementation."
repository = "https://github.com/banyancomputer"
version = "0.1.0"
license = "MIT"
readme = "README.md"
edition = "2021"

[features]

[dependencies]
async-trait = "^0.1"
futures = "^0.3"
thiserror = "^1"
tracing = "^0.1"

[[bin]]
name = "tomblet"
path = "src/main.rs"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "^0.1"
getrandom = { version = "^0.2", features = ["js"] }
js-sys = "^0.3"
tracing-wasm = "^0.2"
wasm-bindgen = "^0.2"
wasm-bindgen-futures = "^0.4"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "^0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "^1", features = ["full"] }
tracing-appender = "^0.2"
tracing-subscriber = { version = "^0.3", features = [
  "env-filter",
  "fmt",
  "time",
] }

[build-dependencies]
time = { version = "^0.3", features = ["formatting"] }
